services:
  ms-relatorio:
    build:
      context: .
      dockerfile: Dockerfile
    image: 'ms-relatorio:0.0.1-SNAPSHOT'
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      - 'SERVER_PORT=8082'
      - 'SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/ms-relatorio'
      - 'SPRING_DATASOURCE_USERNAME=123456'
      - 'SPRING_DATASOURCE_PASSWORD=postgres'
    ports:
      - '8082:8082'

  postgres:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=ms-relatorio'
      - 'POSTGRES_PASSWORD=postgres'
      - 'POSTGRES_USER=123456'
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U 123456 -d ms-relatorio" ]
      interval: 5s
      timeout: 5s
      retries: 10
    ports:
      - '5432:5432'
